name: Deploy CDK (main)

on:
  push:
    branches: [ main ]        # deploy on changes to main
  workflow_dispatch: {}       # allow manual run from Actions tab

permissions:
  id-token: write             # REQUIRED for OIDC
  contents: read

env:
  AWS_REGION: us-west-1       # <-- CHANGE to your target region (e.g., us-west-2)
  CDK_STACKS: MaterialRecognitionServiceCdkStack   # <-- CHANGE after running `npx cdk ls`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::630888664087:role/GitHubCdkDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: CDK Synth
        run: npx cdk synth

      - name: CDK Deploy (no prompts)
        run: npx cdk deploy --require-approval never $CDK_STACKS
